// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnVkGeN9SIjIX8Hm2EJZKQ53HKFLx_nvI',
    appId: '1:692001739783:web:b0f9a5244bbd264e3386a2',
    messagingSenderId: '692001739783',
    projectId: 'tinylines-863ea',
    authDomain: 'tinylines-863ea.firebaseapp.com',
    storageBucket: 'tinylines-863ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrg0igKS80H6iaBGJ_TDOhWxaOc04cqqs',
    appId: '1:692001739783:android:35d7dfba2a04cccb3386a2',
    messagingSenderId: '692001739783',
    projectId: 'tinylines-863ea',
    storageBucket: 'tinylines-863ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl2xVmrtg1K_az_SyEQ8GsTvw0MZpzVG0',
    appId: '1:692001739783:ios:2cb736ade849cd8f3386a2',
    messagingSenderId: '692001739783',
    projectId: 'tinylines-863ea',
    storageBucket: 'tinylines-863ea.firebasestorage.app',
    iosBundleId: 'com.example.tinyLines',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl2xVmrtg1K_az_SyEQ8GsTvw0MZpzVG0',
    appId: '1:692001739783:ios:2cb736ade849cd8f3386a2',
    messagingSenderId: '692001739783',
    projectId: 'tinylines-863ea',
    storageBucket: 'tinylines-863ea.firebasestorage.app',
    iosBundleId: 'com.example.tinyLines',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnVkGeN9SIjIX8Hm2EJZKQ53HKFLx_nvI',
    appId: '1:692001739783:web:ff5a06532baf71683386a2',
    messagingSenderId: '692001739783',
    projectId: 'tinylines-863ea',
    authDomain: 'tinylines-863ea.firebaseapp.com',
    storageBucket: 'tinylines-863ea.firebasestorage.app',
  );
}
