// Mocks generated by Mockito 5.4.6 from annotations
// in tinylines/test/providers/journal_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tinylines/models/journal_entry.dart' as _i2;
import 'package:tinylines/services/firestore_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i4.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.JournalEntry>> loadAllEntries() =>
      (super.noSuchMethod(
            Invocation.method(#loadAllEntries, []),
            returnValue: _i3.Future<List<_i2.JournalEntry>>.value(
              <_i2.JournalEntry>[],
            ),
          )
          as _i3.Future<List<_i2.JournalEntry>>);

  @override
  _i3.Future<void> saveEntry(_i2.JournalEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#saveEntry, [entry]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
