// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArmRvgvfbi2Hs8d-uqhJWtXIRjvdBXHUw',
    appId: '1:1081996176104:web:27499fee60eb23e930f75d',
    messagingSenderId: '1081996176104',
    projectId: 'tinylines-5265e',
    authDomain: 'tinylines-5265e.firebaseapp.com',
    storageBucket: 'tinylines-5265e.firebasestorage.app',
    measurementId: 'G-1Q4BPN5CSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkQNdSka40xy2hA09EoO0dQe_oao5C4ko',
    appId: '1:1081996176104:android:d3630ae6c9cd32fa30f75d',
    messagingSenderId: '1081996176104',
    projectId: 'tinylines-5265e',
    storageBucket: 'tinylines-5265e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0J1ZuOouxkRm2n4Vng2Q31ZqxsNnT8EI',
    appId: '1:1081996176104:ios:efbca11b04efbd9930f75d',
    messagingSenderId: '1081996176104',
    projectId: 'tinylines-5265e',
    storageBucket: 'tinylines-5265e.firebasestorage.app',
    iosBundleId: 'com.example.tinyLines',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0J1ZuOouxkRm2n4Vng2Q31ZqxsNnT8EI',
    appId: '1:1081996176104:ios:efbca11b04efbd9930f75d',
    messagingSenderId: '1081996176104',
    projectId: 'tinylines-5265e',
    storageBucket: 'tinylines-5265e.firebasestorage.app',
    iosBundleId: 'com.example.tinyLines',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArmRvgvfbi2Hs8d-uqhJWtXIRjvdBXHUw',
    appId: '1:1081996176104:web:f48b8cf2e9022aee30f75d',
    messagingSenderId: '1081996176104',
    projectId: 'tinylines-5265e',
    authDomain: 'tinylines-5265e.firebaseapp.com',
    storageBucket: 'tinylines-5265e.firebasestorage.app',
    measurementId: 'G-ES436KJ7C3',
  );

}